<?php

namespace HRT\WP\ThesaurusTaxonomy;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-18 at 04:32:49.
 */
class ThesaurusTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Thesaurus
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Thesaurus;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers HRT\WP\ThesaurusTaxonomy\Thesaurus::get
	 * @todo   Implement testGet().
	 */
	public function testGet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
