<?php

namespace HRT\WP\ThesaurusTaxonomy;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-18 at 04:32:52.
 */
class PostsTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Posts
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Posts;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}
